# Generated by Django 3.2 on 2022-01-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('size', models.PositiveSmallIntegerField(choices=[(2, 2), (4, 4), (6, 6), (8, 8)])),
            ],
            options={
                'ordering': ['size'],
            },
        ),
    ]
