# Generated by Django 3.2 on 2022-01-14 17:07

import booking.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=booking.models.NameField(max_length=15, unique=True),
        ),
    ]
