# Generated by Django 3.2 on 2022-02-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20220218_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
